name: Notify Telegram

permissions:
  contents: read

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            📣 *New Pull Request Opened!*

            🔹 *Title:* ${{ github.event.pull_request.title }}
            👤 *Author:* @${{ github.event.pull_request.user.login }}
            🌿 *Branch:* `${{ github.event.pull_request.head.ref }}` 👉 `${{ github.event.pull_request.base.ref }}`
            🔗 [View Pull Request](${{ github.event.pull_request.html_url }})
